---
title: "Cognitive and ecological aspects determine cleaner performance"
author:
- Andrés E. Quiñones^[Laboratorio de Biología Evolutiva de Vertebrados, Departamento
  de Ciencias Biológicas, Universidad de los Andes, Bogotá, Colombia - andresqp@gmail.com]
- Zegni Triki^[Department of Zoology, Stockholm University, Stockholm, Sweden]
- Redouan Bshary^[Institute of Biology, University of Neuchâtel, Neuchâtel, Switzerland]
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document: default
  word_document: default
fig_caption: yes
fontsize: 12pt
header-includes:
- \usepackage{float}
- \usepackage{setspace}\doublespacing
- \linespread{2}
- \usepackage{lineno}
- \linenumbers
keep_tex: yes
keywords: My keywords
linespread: 2
bibliography: Cleaner_learning.bib
style: C:\Users\andre\Zotero\styles\behavioral-ecology-and-sociobiology.csl
spacing: double
abstract: My abstract.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Cooperation among individuals of the same or different species is ubiquitous in nature. 
Among individuals of the same species it is the basis for the evolution of  higher 
forms of biological organization [@maynardsmith_Major_1998]. 
Among individuals of different species it underlays the biological mechanism for 
fundamental ecological interactions such as pollination, nitrogen fixation or 
parasite removal [@begon_Ecology_2006]. However, when cooperation is costly, 
it is not straigtforward to understand why individuals would be willing to pay that cost [@lehmann_Evolution_2006]. Furthermore, cooperative interactions might open the way for 
one partner to exploit the other, what prevents this type of exploitation? [@herre_Evolution_1999]
One reason for cooperating is if the benefits obtained from a partner´s 
cooperative action are dependent on one's own cooperative act. 
This dependency can arise, for instance, when cooperative partners
choose who they interact with depending on the level of cooperation they offer. 
In line with this, cooperative interactions can be viewed as a market-like situation 
where partner choice mediates the level of exchange between traders [@hammerstein_Biological_2016; @leimar_Cooperation_2010; @noe_Biological_1994a]. Empirical evidence shows
that several iconic examples of cooperation between individuals of different species 
are indeed mediated by partner choice [@hammerstein_Biological_2016]. Biological market theory highlights 
that changes in the supply and demand of goods and services determines the value of 
those commodities, and therefore, can influence partner's actions in the cooperative 
exchange. For instance, in the marine cleaning mutualism, where cleaner fish 
_Labroides dimidiatus_ (cleaners) removes ectoparasites from other coral reef fishes (clients) [@cote_Evolution_2000],
some client species are able to choose among different cleaners, and because of this
obtain better service [@grutter_Cleaner_2003]. Better services means for clients to have priority when 
more than one client is available [@bshary_Choosy_2002], and less cheating (when cleaners eat live tissue
instead of parasites) [@grutter_Cleaner_2003]. However, recent evidence shows that when clients experience
ecological conditions with low cleaner abundance, they are less likely to use partner
choice to leverage better service [@triki_Biological_2019]. On the other side, 
cleaners in those markets with favourable conditions, stop giving priority to choosy clients [@triki_Biological_2019; @triki_Decrease_2018]. Thus, it seems that cleaners, as well as clients,
adjust their strategy to the prevalent market conditions they find in their environment. 
This adjustement cannot be due to local genetic adaptation, given that cleaners are open water spawners 
and the environmental changes in different sites have occured in the last decade [@triki_Biological_2019; @triki_Decrease_2018]. Alternatively, a recent cognitive model proposes that differences in 
cleaners preferences can arise trough the interaction of cleaner's cognitive processes 
with the environmental conditions [@quinones_Reinforcement_2019]. Under this view,
cleaners ontogenatically develop their preferences for different clients through learning,
and some environmental conditions facilitate learning. Thus, the adaptive adjustment 
seen in cleaners might be due to their learning mechanisms. Despite the general fit of the 
model explanation to the available data, no systematic parameter fit has been performed to 
evaluate which combination of model parameters better fit the data. 

## Methods

In order to fit the model parameters to the data we used Aproximate Bayesian Computation (ABC). ABC is a statistical technique to fit parameters of complicated models to data when we can't explicitely compute the likelihood as a function of the model parameters. Instead, we can compare the outcome of the model, given a set of parameters, to the actual data usually using a set of summary statistics that summarize the fit of the model predictions to the data [@beaumont_Approximate_2010a]. Thus, individual-based models such as the ones developed under the framework of reinforcement learning would be amenable to fit with this technique. In here, we will use the data from @triki_Biological_2019 to fit the parameters of the  model analyzed in @quinones_Reinforcement_2019. 

The model consist of a set individual-simulations where individuals face a series of choices; they have to choose between two options. Individuals in the model represent cleaners, and the options they face simulate the natural conditions of a cleaning market. Thus, individual in the model choose to prioritize  different clients. These clients are classified in resident and visitors. Residents are those clients that stay in the cleaning queue when they are not given priority; while visitors leave (with a certain probability) the queue after they are not given priority. Individuals obtain reward from cleaning a client regardless of the type.  Everytime individuals face and make a choice they update the probability of making that same choice. The update is based on the difference between the expectation of reward and the actual reward the individual obtains (prediction error); and it is carried in the direction that would lead to more reward given the new information. Further details of the model implementation can be found in the paper [@quinones_Reinforcement_2019]. The model analysis points to the relevance of two parameters. First, $\gamma$ measures how much individuals include future rewards in their desicion updates. If $\gamma=0$, individuals only use the immediate reward obtained from a cleaning interaction. As $\gamma$ increases individuals include more, in their desicion making, the reward obtained from the subsequent choices. That amounts to calculating and using for deision making future expected rewards. Second, $\eta$ measures how much individuals include in their reward the fleeing behaviour of visitor clients as a negative component. Both of these components allow individuals to use in ther estimates the future effects of their choices. The model analysis shows that without either of them, learning individuals can't develop a preference for the visitor client. The analysis contrast the effect of these two parameters agaisnt variation in the relative abundance of the two client types. The analysis shows that under very high client abundance the presence of  future rewards ($\gamma>0$) no longer favour the preference for the ephemeral clients, this effect does not occur with negative reward mediated by client behaviour ($\eta$). Thus, the analysis suggests that future reward as an explanation for cleaner ability to prefer visitors is supported by @triki_Biological_2019 data. However, a combination of future and negative rewards, could be a better explanation for the data. In the current analysis, we will use the data from @triki_Biological_2019 to fit some of the model parameters, particularly relevant we will fit $\gamma$ and $\eta$ to find out whether each or a combination of these effects is a better explanation for the pattern seen in the data. 

### Data explanation

*Insert here brief description of the data and data collection*

In order to capture with the model the relationship between the characteristics of the market and the cleaner's performance we need to translate the absolute abundances of the data to relative abundances. This is because in the model, relative abundances of clients define not only the probability of residents and visitors, but also how often the cleaning station is empty (e.g. there are no clients to be cleaned). Thus, we computed a measure of cleaner abundance for each site relative to total absolute abundances of cleaners and clients. As for the client abundances for residents and visitors we computed a relative measure with respect with the total client abundance, and weigthted that by the relative absence of cleaners (1-relative cleaner abundance). Thus, all three measures of relative abundance sum up to 1, and can be used in the model as a proxy for the probability of having different options in the cleaning station. This translation between absolute and relative abundances is not without caveats. For instance, how busy a particular cleaning station is, should depend not only on the absolute abundaces of clients, but also on how often they require cleaning services. How often the services are needed in turn should depend on things like parasite abundances. These caveats are relevant because they will influence the estimates of the model parameters. Nevertheless, we can use the translation and the model estimates to shed some light on the cognitive mechanisms that better explain the behaviour of cleaners. 

### Results






## Cited literature